### ISSUE TITLE
the meaning of each element in c1

### ISSUE THREAD

**Issue by xiaoyun4** [ishit/L1Stabilizer#1]
1. in optimizeTransforms.m, 
% Weighting of 100:1 for affine to translational parts
c1 = [1 1 100 100 100 100]';
Even though you said weighting of 100:1 for affine to translational parts,  i still can not understand the meaning of each element in C1, can you explain it?

2. when i run 'main.m' for  my own video, but the new camera path that i get is horizontal line in figure 1 or figure 2 about the movement of x or y axis.   
can you tell me how to adjust the parameter so that  the movement of x or y axis for new camera path is match the  movement of x or y axis for original camera path?

Thanks a lot

**Comment by ishit** [comment]
> in optimizeTransforms.m,
% Weighting of 100:1 for affine to translational parts
c1 = [1 1 100 100 100 100]';
Even though you said weighting of 100:1 for affine to translational parts, i still can not understand the meaning of each element in C1, can you explain it?

If you refer to the original paper, the affine parameters are scaled to make sure they have an equal footing in the final optimization function. 100:1 means that the affine parameters are multiplied by a factor of 100.

> when i run 'main.m' for my own video, but the new camera path that i get is horizontal line in figure 1 or figure 2 about the movement of x or y axis.
can you tell me how to adjust the parameter so that the movement of x or y axis for new camera path is match the movement of x or y axis for original camera path?

Try tweaking w1, w2 and w3.
https://github.com/ishit/L1Stabilizer/blob/5dff5b16bf4afd5ecd115ef792b5a24e06fa1bdb/optimizeTransforms.m#L23

**Comment by zhanghuanran** [comment]
would you have realized the part of wobble suppression?  I want to ask for about this.

**Comment by xccoming** [comment]
in getTransforms.m,
transforms{k} = estimateGeometryTransform(matched_b', matched_a‘.........)
why estimate transform from cur frame to previous frame , not inverse ?

**Comment by shaozhaizj1125** [comment]
if a L2 item is  added to the energy function, how can we use codes to realize it.

**Comment by ishit** [comment]
Change optimizeTransforms.m accordingly.
https://github.com/ishit/L1Stabilizer/blob/5dff5b16bf4afd5ecd115ef792b5a24e06fa1bdb/optimizeTransforms.m#L65
